# Generated by Django 4.2.7 on 2026-01-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'In (Deposit)'), ('out', 'Out (Withdrawal)')], max_length=10)),
                ('category', models.CharField(choices=[('sale', 'Sale Revenue'), ('inventory', 'Inventory Purchase'), ('expense', 'Business Expense'), ('owner_draw', 'Owner Drawing (Equity Withdrawal)'), ('owner_capital', 'Owner Capital Injection'), ('transfer', 'Internal Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_drawing_record', to='inventory.banktransaction')),
            ],
        ),
        migrations.AddField(
            model_name='stockin',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Account used to pay for this stock', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.bankaccount'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Account receiving the payment (if Transfer)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.bankaccount'),
        ),
    ]
