# Generated by Django 4.2.7 on 2026-01-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bankaccount_banktransaction_ownerdrawing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdrawing',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank Account to withdraw from', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.bankaccount'),
        ),
    ]
