# Generated by Django 4.2.7 on 2026-01-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ownerdrawing_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the original sale')),
                ('sku', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Original Cost Price per unit', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Original Selling Price per unit', max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='e.g. Old Invoice #', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
