# Generated by Django 4.2.7 on 2026-01-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sale_delete_stockout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSale',
        ),
    ]
